Stop statically including IndentingPrintWriter in VCN service
VCN service depends on LocalLog.java and WakeupMessage.java. Previously
VCN service will statically include framework-connectivity-shared-srcs
filegroup that has the two required classes. To avoid name class
conflicts, all classes in this filegroup need to be jarjared.

As results, VCN service will use a jarjared IndentingPrintWriter. During
dumpsys, VcnManagementService#dump will create a IndentingPrintWriter
and pass it to VcnUnderlyingNetworkTemplate#dump. Then because
VcnUnderlyingNetworkTemplate fails to recognize the jarjared class, it
will throw NoSuchMethodError.

This issue only exists when VCN is in the platform. When VCN is built
into Tethering module, a different build architecture is used and this
issue will be gone.

This patch fixes the NoSuchMethodError issue by creating temporary
copies of LocalLog and WakeupMessage and updating VCN service to
statically include them. When VCN modularization is fully done, these
two copies can be removed

Bug: 386225194
Test: atest CtsVcnTestCases && atest FrameworksVcnTests
Test: adb dumpsys vcn_management
Flag: EXEMPT; low risk and small scope bug fix
Change-Id: Ie5c099ac04133093c23f8ef6181bab08d1bf8e4b